[package]
name    = "tam-pipeline"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
blake3 = "1"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif"] }
tam-limits = { path = "../tam-limits" }
tam-types = { path = "../tam-types" }
zip = { version = "2", default-features = false, features = ["deflate"] }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor"] }
zip = { version = "2", default-features = false, features = ["deflate"] }

[lints]
workspace = true
