[package]
name    = "tam-marketplace-tpt"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
base64 = "0.22"
md-5 = "0.10"
reqwest = { version = "0.12", default-features = false, features = [
  "rustls-tls",
  "json",
  "multipart",
] }
serde_json = "1"
tam-marketplace = { path = "../tam-marketplace" }
tam-types = { path = "../tam-types" }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
