[package]
name    = "tam-marketplace"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tam-types = { path = "../tam-types" }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor"] }

[lints]
workspace = true
